---
- name: Install Packages/Git Repos for both RHUA & CDS
  hosts: rhua:cds
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: get epel-repo rpm RHEL6
      get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
      when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6

    - name: install epel-repo rpm
      action: yum pkg=/tmp/epel-release.rpm state=installed

    - name: update firewall
      action: copy src="files/${item}" dest="/${item}" owner=root group=root
      with_items:
        - etc/sysconfig/iptables
      notify: restart iptables

    - name: install extra rpms to make devel env nicer
      action: yum name=$item state=present
      with_items:
        - vim-enhanced
        - git
        - tig

    - name: scp sample .rc files over to hosts to make editing easier for root
      action: copy src="files/${item}" dest="/root/.${item}" owner=root group=root
      with_items:
        - bashrc
        - vimrc

    - name: scp sample .rc files over to hosts to make editing easier for ec2-user
      action: copy src="files/${item}" dest="/home/ec2-user/.${item}" owner=ec2-user group=ec2-user
      with_items:
        - bashrc
        - vimrc

    - name: Ensure /git exists
      file: dest=/git state=directory

    - name: Git checkout pulp 'rhui' branch
      action: git repo=https://github.com/splice/pulp.git dest=/git/pulp version=rhui

    - name: Git checkout gofer 'rhui' branch
      action: git repo=https://github.com/splice/gofer.git dest=/git/gofer version=rhui

    - name: Git checkout grinder 'rhui' branch
      action: git repo=https://git.fedorahosted.org/git/grinder.git dest=/git/grinder version=rhui

  handlers:
    - name: restart iptables
      action: service name=iptables state=restarted


- name: Install Packages/Git Repos for RHUA
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  vars:
    - rhui_build_host: ec2-50-17-26-28.compute-1.amazonaws.com

  tasks:

    - name: install rhui testing yum repo
      command: wget -O /etc/yum.repos.d/testing_rpms_rhui.repo http://${rhui_build_host}/pub/testing_rpms_rhui.repo

    - name: install pulp
      action: yum name=${item} state=latest disablerepo=epel
      with_items:
        - pulp
        - qpid-cpp-server-ssl
        - policycoreutils-python
        - pulp-admin
        - pulp-selinux-server
        - pulp-consumer
        - mod_wsgi
        - gofer
        - gofer-package
        - rh-rhua-selinux-policy
      notify: restart httpd

    # Note mongodb requires a few minutes to preallocate it's db files
    # We are starting mongodb now so while other tasks run it's DB files will be preallocated
    - name: enable mongodb
      action: service name=mongod state=started enabled=yes

    - name: install rhui-tools
      action: yum name=${item} state=latest
      with_items:
        - rh-rhui-tools

    - name: Create NSS certificates for qpid
      command: /usr/bin/nss-db-gen

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted

- name: Install Packages/Git Repos for CDS
  hosts: cds
  user: ec2-user
  sudo: yes
  gather_facts: true

  vars:
    - rhui_build_host: ec2-50-17-26-28.compute-1.amazonaws.com

  tasks:

    - name: install rhui testing yum repo
      command: wget -O /etc/yum.repos.d/testing_rpms_rhui.repo http://${rhui_build_host}/pub/testing_rpms_rhui.repo

    - name: install pulp-cds
      action: yum name=${item} state=latest
      with_items:
       - pulp-cds
       - pulp-selinux-server
       - grinder
       - gofer
       - gofer-package
       - mod_wsgi
       - python-gofer
       - rh-rhui-tools-debug-script
      notify: restart httpd

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted

