---
# ansible-playbook rhui_dev_setup.yml -vv --private-key=~/.ssh/splice_rsa

- name: Stage instance(s)
  hosts: localhost
  connection: local
  user: root
  gather_facts: false
  
  tags:
      - stage

  vars:
      keypair: splice
      instance_type: m1.large
      rhua_security_group: rhui_dev_rhua
      cds_security_group: rhui_dev_cds
      client_security_group: rhui_dev_client
      image: ami-f6f16b9f
      cds_instance_count: 2

  # Launch 1 RHUA, 2 CDS

  tasks:
    - name: Launch RHUA instance
      local_action: ec2 keypair=${keypair} group=${rhua_security_group} instance_type=${instance_type} 
        image=${image} wait=no count=1
      register: ec2_rhua

    - name: Launch CDS instance(s)
      local_action: ec2 keypair=${keypair} group=${rhua_security_group} instance_type=${instance_type} 
        image=${image} wait=no count=${cds_instance_count}
      register: ec2_cdses

    - name: Add rhua instances to rhua group
      local_action: add_host name=${item.public_dns_name} groups=rhua
      with_items: ${ec2_rhua.instances}

    - name: Add cds instances to cds group
      local_action: add_host name=${item.public_dns_name} groups=cdses
      with_items: ${ec2_cdses.instances}

    - name: Create a volume and attach for RHUA
      local_action: ec2_vol volume_size=100 instance=${item.id}
      with_items: ${ec2_rhua.instances}

    - name: Create a volume and attach for CDSes
      local_action: ec2_vol volume_size=100 instance=${item.id}
      with_items: ${ec2_cdses.instances}

    - name: Wait for SSH to be available on RHUA 
      local_action: wait_for host=${item.public_dns_name} port=22
      with_items: ${ec2_rhua.instances}

    - name: Wait for SSH to be available on CDS(s)
      local_action: wait_for host=${item.public_dns_name} port=22
      with_items: ${ec2_cdses.instances}


- name: Configure RHUA
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tags:
    - config
    - configure 

  tasks:
    - name: install rpms
      action: yum name=$item state=present
      with_items:
        - httpd
        - vim-enhanced
      notify: restart httpd

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted


- name: Configure CDS
  hosts: cdses
  user: ec2-user
  sudo: yes
  gather_facts: true

  tags:
    - config
    - configure 

  tasks:
    - name: install rpms
      action: yum name=$item state=present
      with_items:
        - httpd
        - vim-enhanced
      notify: restart httpd

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
