---
- name: Execute setup scripts on RHUA
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:

    - name: scp setup scripts to RHUA
      action: copy src="../install/${item}" dest="/home/ec2-user/${item}" owner=ec2-user
      with_items:
        - gen_certs.sh
        - update_answers.sh
        - rhui_answers.template
        - vars
        - ent_cert.pem
        - redhat-uep.pem

    - name: scp rhui hostname env file
      action: copy src="../hostnames.env" dest="/home/ec2-user/hostnames" owner=ec2-user

    - name: Generate X509 certificates
      command: sudo /home/ec2-user/gen_certs.sh chdir=/home/ec2-user

    - name: Update RHUI answers file
      command: sudo /home/ec2-user/update_answers.sh chdir=/home/ec2-user

    - name: Run rhui-installers
      command: sudo rhui-installer /home/ec2-user/rhui.answers chdir=/home/ec2-user

    #- name: Fetch CDS rpms from RHUA
    #  action: fetch src=/tmp/rhui/${item} dest=./${item} flat=true
    #  with_items:
    #    - rh-cds1-config-2.1-2.el6.noarch.rpm
    #    - rh-cds2-config-2.1-2.el6.noarch.rpm

    - name: Install rh-rhua-config on RHUA
      action: shell yum -y --nogpgcheck localinstall /tmp/rhui/rh-rhua-config*

####
# Performing below copy & install steps in shell script
#  - Don't know how to use ansible and ensure that rh-cds1-config* gets scpd to CDS01
#    and rh-cds2-config gets scpd to CDS02.
#  - Will keep this logic in a shell script, until we learn of a better solution
####
- name: Copy and install generated config RPMs
  hosts: localhost
  connection: local
  user: root
  gather_facts: false

  tasks:
    - name: Gather config rpms to localhost
      local_action: shell cd ../install && gather_config_rpms_from_rhua.sh

    - name: SCP config rpms to CDSes
      local_action: shell cd ../install && scp_config_rpms_to_cds.sh

    - name: Install config rpms on CDSes
      local_action: shell cd ../install && install_config_rpms.sh

- name: Run pulp-server init
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: pulp-server init
      action: shell service pulp-server init


- name: Restart Services on RHUA
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: restart pulp-server
      action: service name=pulp-server state=restarted


- name: Restart Services on CDS
  hosts: cds
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: restart pulp-cds
      action: service name=pulp-cds state=restarted

    - name: restart goferd
      action: service name=goferd state=restarted





