---

- name: Install Packages/Git Repos
  hosts: rhua:cds
  user: ec2-user
  sudo: yes
  gather_facts: true

  tags:
    - rpms_and_code

  tasks:
    - name: get epel-repo rpm RHEL6
      get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
      when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6

    - name: install epel-repo rpm
      action: yum pkg=/tmp/epel-release.rpm state=installed

    # TODO:
    #  After RHUI's yum repo is ready to use, update this to install pulp from RPM to pick up deps.
    #- name: install pulp v1-stable repo to pick up dependencies
    #  action: yum conf_file=http://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo disablerepo=* enablerepo=pulp-v1-stable name=pulp state=present

    - name: install pulp deps from rhel/epel
      action: yum name=$item state=present
      with_items:
        - pymongo
        - python-setuptools
        - python-webpy
        - python-simplejson
        - python-oauth2
        - python-isodate
        - python-BeautifulSoup
        - httpd
        - mod_ssl
        - openssl
        - python-ldap
        - crontabs
        - acl
        - mongodb-server
        - mongodb
        - qpid-cpp-server
        - python-ctypes
        - python-hashlib
        - nss
        - curl
        - python-rhsm

    # RPMs from Pulp project
    # python-gofer, grinder, gofer, gofer-package, M2Crypto, mod_wsgi

    - name: install extra rpms to make devel env nicer
      action: yum name=$item state=present
      with_items:
        - vim-enhanced
        - git
        - tig

    - name: Ensure /git exists
      file: dest=/git state=directory

    - name: Git checkout pulp 'rhui' branch
      action: git repo=https://github.com/splice/pulp.git dest=/git/pulp version=rhui

    - name: Git checkout gofer 'rhui' branch
      action: git repo=https://github.com/splice/gofer.git dest=/git/gofer version=rhui

    - name: Git checkout grinder 'rhui' branch
      action: git repo=https://git.fedorahosted.org/git/grinder.git dest=/git/grinder version=rhui

    - name: Setup devel env for Pulp
      command: echo "Steps T.B.D."
      notify: restart httpd

    - name: scp sample .rc files over to hosts to make editing easier for root
      action: copy src="files/${item}" dest="/root/.${item}" owner=root group=root
      with_items:
        - bashrc
        - vimrc

    - name: scp sample .rc files over to hosts to make editing easier for ec2-user
      action: copy src="files/${item}" dest="/home/ec2-user/.${item}" owner=ec2-user group=ec2-user
      with_items:
        - bashrc
        - vimrc

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
