---
# ansible-playbook simple.yml -vv --private-key=~/.ssh/splice_rsa

- name: Stage instance(s)
  hosts: localhost
  connection: local
  user: root
  gather_facts: false

  tags:
      - stage

  vars:
      keypair: splice
      instance_type: m1.large
      rhua_security_group: rhui_dev_rhua
      cds_security_group: rhui_dev_cds
      client_security_group: rhui_dev_client
      image: ami-f6f16b9f
      cds_instance_count: 2
      rhui_hosts_file: "{{ lookup('env', 'RHUI_HOSTS_FILE') }}"
      ebs_pulp_data_size: 100
      ebs_pulp_data_part: sdh

#TODO
# Look into launching with an increase root EBS volume
#  OR add a second volume for Mongo /var/lib/mongo
#  Another for logs /var/log

  # Launch 1 RHUA, 2 CDS

  tasks:
    - local_action: shell id -u -n
      register: user_name

    - local_action: shell date +"%Y-%m-%d"
      register: datestamp

    - name: Launch RHUA instance
      local_action:
        module: ec2
        keypair: ${keypair}
        group: ${rhua_security_group}
        instance_type: ${instance_type}
        image: ${image} 
        wait: yes
        count: 1
        instance_tags: '{"Name": "{{ user_name.stdout }} RHUA {{ datestamp.stdout }}"}'
      register: ec2_rhua

    - name: Add rhua instances to rhua group
      local_action: add_host name=${item.public_dns_name} groups=rhua
      with_items: ${ec2_rhua.instances}

    - name: Add rhua group to servers group
      local_action: add_host name=${item.public_dns_name} groups=servers
      with_items: ${ec2_rhua.instances}

    - name: Create a volume for pulp content and attach for the rhua
      local_action: ec2_vol volume_size=${ebs_pulp_data_size} instance=${item.id} device_name=${ebs_pulp_data_part}
      with_items: ${ec2_rhua.instances}

    - name: Wait for SSH to be available on all servers
      local_action: wait_for host=${item} port=22
      with_items: ${groups.servers}

    - name: Write [rhua] header into {{rhui_hosts_file}}
      local_action: shell echo '[rhua]' >> ${rhui_hosts_file}
    
    - name: Write rhua info into {{rhui_hosts_file}}
      local_action: shell echo '{{ item.1 }}' >> ${rhui_hosts_file}
      with_indexed_items: ${groups.rhua}

- name: Configure Servers
  hosts: servers
  user: ec2-user
  sudo: yes
  gather_facts: true

  tags:
    - config

  vars:
    - ebs_pulp_part: /dev/xvdl
    - rhua_vg: vg0
    - rhua_vol_name: vol1
    - var_lib_pulp_part: /dev/${rhua_vg}/${rhua_vol_name}

  tasks:
    - name: Create PV for Volume group
      command: pvcreate ${ebs_pulp_part}

    - name: Create Volume Group
      command: vgcreate ${rhua_vg} ${ebs_pulp_part}

    - name: Create Logical Volume
      command: lvcreate -l 100%FREE -n ${rhua_vol_name} ${rhua_vg}

    - name: Create filesystem on new LV
      command: /sbin/mkfs.ext3 ${var_lib_pulp_part}

    - name: Create /var/lib/pulp mount point 
      command: mkdir /var/lib/pulp

    - name: Mount EBS volume
      action: mount name=/var/lib/pulp src=${var_lib_pulp_part} fstype=ext3 state=mounted

    - name: get epel-repo rpm RHEL6
      get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
      when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6

    - name: install epel-repo rpm
      yum: pkg=/tmp/epel-release.rpm state=installed

    - name: install rpms
      action: yum name=$item state=present
      with_items:
        - httpd
        - vim-enhanced
        - git
        - tig
      notify: restart httpd
 
    - name: Git checkout
      action: git repo=https://github.com/splice/pulp.git dest=/git/pulp

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted

