---
- name: Execute setup scripts on RHUA
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true
  vars:
      answers_file: "/home/ec2-user/rhui-certs/answers"
  

  tasks:

    - name: scp setup scripts to RHUA
      action: copy src="../install/${item}" dest="/home/ec2-user/${item}" owner=ec2-user mode=0775
      with_items:
        - gen_certs.sh
        - vars
        - redhat-uep.pem

    - name: scp rhui hostname env file
      action: copy src="../hostnames.env" dest="/home/ec2-user/hostnames" owner=ec2-user

    - name: Generate X509 certificates
      command: sudo /home/ec2-user/gen_certs.sh chdir=/home/ec2-user

    - name: Run rhui-installers
      command: sudo rhui-installer ${answers_file} chdir=/home/ec2-user

    #- name: Fetch CDS rpms from RHUA
    #  action: fetch src=/tmp/rhui/${item} dest=./${item} flat=true
    #  with_items:
    #    - rh-cds1-config-2.1-2.el6.noarch.rpm
    #    - rh-cds2-config-2.1-2.el6.noarch.rpm

    - name: Install rh-rhua-config on RHUA
      action: shell yum -y --nogpgcheck localinstall /etc/rhui/rh-rhua-config*

####
# Performing below copy & install steps in shell script
#  - Don't know how to use ansible and ensure that rh-cds1-config* gets scpd to CDS01
#    and rh-cds2-config gets scpd to CDS02.
#  - Will keep this logic in a shell script, until we learn of a better solution
####
- name: Copy and install generated config RPMs
  hosts: localhost
  connection: local
  user: root
  gather_facts: false

  tasks:
    - name: Gather config rpms to localhost
      local_action: shell cd ../install && ./gather_config_rpms_from_rhua.sh

    - name: SCP config rpms to CDSes
      local_action: shell cd ../install && ./scp_config_rpms_to_cds.sh

    - name: Install config rpms on CDSes
      local_action: shell cd ../install && ./install_config_rpms.sh

- name: Run pulp-server init
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: pulp-server init
      action: shell service pulp-server init


- name: Restart Services on RHUA
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: restart pulp-server
      action: service name=pulp-server state=restarted


- name: Restart Services on CDS
  hosts: cds
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:
    - name: restart pulp-cds
      action: service name=pulp-cds state=restarted

    - name: restart goferd
      action: service name=goferd state=restarted


- name: rhui-manager initial setup with CA 
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:

    - name: scp script to create initial user
      action: copy src="../install/rhui_manager_initial_setup.sh" dest="/home/ec2-user/rhui_manager_initial_setup.sh" owner=ec2-user mode=0775

    - name: run rhui-manager for first time and give it path to CA
      action: shell sudo /home/ec2-user/rhui_manager_initial_setup.sh


- name: Upload content certificate
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true
  vars:
    content_cert: ent_cert.pem

  tasks:

    - name: scp script to create initial user
      action: copy src="../install/${content_cert}" dest="/root/${content_cert}" owner=root group=root mode=0664

    - name: upload content cert to rhui-manager
      action: shell sudo rhui-manager --username admin --password admin cert upload --cert /root/${content_cert}


- name: Register CDS1 and CDS2
  hosts: rhua
  user: ec2-user
  sudo: yes
  gather_facts: true

  tasks:

    - name: scp script to create initial user
      action: copy src="../install/${item}" dest="/home/ec2-user/${item}" owner=ec2-user group=ec2-user mode=0775
      with_items:
        - rhui_manager_initial_cds_setup.sh

    - name: add both CDSes to RHUI
      action: shell sudo ./rhui_manager_initial_cds_setup.sh 
