- name: scp iso file 
  action: copy src="{{iso_path}}" dest="/root/" owner=root group=root

- name: create mount point
  command: mkdir -p /mnt/rhui

- name: mount iso
  shell: mount -o loop /root/{{rhui_iso_filename}} /mnt/rhui

- name: setup rhui-installer
  action: shell cd /mnt/rhui && ./setup_package_repos --nogpgsigs # TODO: This needs to be removed for production ISOs
  
- name: install util rpms
  command: sudo yum install -y {{item}}
  with_items:
   - bind-utils
