- name: copy
  become: true
  shell: cp -r /mnt/rhui/* /home/ec2-user/
- name: chmod
  become: true
  shell: chmod a+x /home/ec2-user/install*
- name: show
  become: true
  command: pwd
- name: show
  become: true
  command: ls -larht
- name: install 
  become: true
  shell: ./install_RHUA.sh
  ignore_errors: true
- name: install 
  become: true
  shell: ./install_tools.sh

#- name: install pulp
#  shell: cd /mnt/rhui && bash install_RHUA.sh
#  ignore_errors: yes # this is to workaround ISO where install_RHUA.sh was not setup w/ +x permission

# this is to workaround ISO where install_RHUA.sh was not setup w/ +x permission
#- name: install tools
#  shell: cd /mnt/rhui && bash install_tools.sh

# Note mongodb requires a few minutes to preallocate it's db files
# We are starting mongodb now so while other tasks run it's DB files will be preallocated
- name: enable mongodb
  action: service name=mongod state=started enabled=yes

- name: Create NSS certificates for qpid
  command: /usr/bin/nss-db-gen

# This is a hack until a new ISO are built
- name: scp new rh-rhui-tool rpms
  action: copy src="./{{item}}" dest="/root/{{item}}" owner=root group=root
  with_items:
    - rh-rhui-tools-2.1.41-1.el6.noarch.rpm
    - rh-rhui-tools-debug-script-2.1.41-1.el6.noarch.rpm  
- name: install new rh-rhui-tools
  become: true
  shell: yum localinstall -y /root/rh-rhui-tools-debug-script-2.1.41-1.el6.noarch.rpm /root/rh-rhui-tools-2.1.41-1.el6.noarch.rpm
