- name: Backup old ssl configuration
  command: mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.bak

- name: Copy and install new ssl configuration
  copy: 
    src: "files/ssl.conf" 
    dest: "/etc/httpd/conf.d/ssl.conf" 
    owner: root
    group: root
    mode: 0644


- name: Generate DH params for cert
  command: openssl dhparam -out /etc/pki/cds/dh2048.pem 2048

- name: Backup old ssl cert
  command: cp /etc/pki/cds/cds-ssl-cert.crt /etc/pki/cds/cds-ssl-cert.crt.bak

- name: Concate DH params to SSL cert
  command: cat /etc/pki/cds/dh2048.pem >> /etc/pki/cds/cds-ssl-cert.crt
  ignore_errors: yes

- name: restart httpd
  action: service name=httpd state=restarted
