- name: Install packages for monitoring
  hosts: MON_SERV 
  user: ec2-user
  become: true
  gather_facts: true

  tasks:
    - include: tasks/monitoring_service_install.yml
    
    - include: tasks/set_ntp.yml
