- name: scp iso file 
  action: copy src="${iso_path}" dest="/root/rhui.iso" owner=root group=root

- name: create mount point
  command: mkdir -p /mnt/rhui

- name: mount iso
  command: mount -o loop /root/rhui.iso /mnt/rhui
