---

- name: Install Packages
  hosts: builders
  user: ec2-user
  sudo: yes
  gather_facts: true

  tags:
    - packages

  tasks:
    - name: get epel-repo rpm RHEL6
      get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
      when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 6

    - name: install epel-repo rpm
      action: yum pkg=/tmp/epel-release.rpm state=installed

    - name: install deps we will need to build RPMs
      action: yum name=$item state=present
      with_items:
        - tito
        - git
        - tig
        - python2-devel
        - hardlink 
        - gcc
        - mod_ssl
        - openssl
        - openssl-devel
        - swig
        - httpd
        - httpd-devel
        - mongodb-server
        - mongodb
        - pymongo
        - python-setuptools
        - python-BeautifulSoup
        - python-webpy
        - PyYAML
        - python-simplejson
        - python-oauth2
        - python-ldap
        - crontabs
        - acl
        - qpid-cpp-server
        - python-ctypes
        - python-hashlib
        - nss
        - curl
        - python-rhsm
        - ruby
      notify: restart httpd

    - name: install extra rpms to make devel env nicer
      action: yum name=$item state=present
      with_items:
        - vim-enhanced

    - name: update firewall
      action: copy src="files/${item}" dest="/${item}" owner=root group=root
      with_items:
        - etc/sysconfig/iptables
      notify: restart iptables

    - name: scp sample .rc files over to hosts to make editing easier for root
      action: copy src="files/${item}" dest="/root/.${item}" owner=root group=root
      with_items:
        - bashrc
        - vimrc

    - name: scp sample .rc files over to hosts to make editing easier for ec2-user
      action: copy src="files/${item}" dest="/home/ec2-user/.${item}" owner=ec2-user group=ec2-user
      with_items:
        - bashrc
        - vimrc

    - name: Ensure /home/ec2-user/build_scripts exists
      file: dest=/home/ec2-user/build_scripts state=directory owner=ec2-user

    - name: scp python build scripts to generate yum repo
      action: copy src="build_scripts/${item}" dest="/home/ec2-user/build_scripts" owner=ec2-user group=ec2-user
      with_items:
        - bos.cfg
        - bos.py
        - build_repo.sh

    - name: Ensure /home/ec2-user/rpm-deps/el6/x86_64 exists
      file: dest=/home/ec2-user/rpm-deps/el6/x86_64 state=directory owner=ec2-user

    - name: Ensure /var/www/html/pub exists
      file: dest=/var/www/html/pub state=directory owner=ec2-user

  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
    - name: restart iptables
      action: service name=iptables state=restarted
